config_rewrite: replace
langcode: en
status: true
dependencies:
  module:
    - system
  theme:
    - acm_demo_theme
_core: {  }
id: acm_powered
theme: acm_demo_theme
region: footer_first
weight: -6
provider: null
plugin: system_powered_by_block
settings:
  id: system_powered_by_block
  label: 'Powered by Drupal'
  provider: system
  label_display: '0'
visibility: {  }
