config_rewrite: replace
langcode: en
status: true
dependencies:
  module:
    - help
  theme:
    - acm_demo_theme
_core: {  }
id: acm_help
theme: acm_demo_theme
region: content
weight: -6
provider: null
plugin: help_block
settings:
  id: help_block
  label: Help
  provider: help
  label_display: '0'
visibility: {  }
