config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - views.view.products
  module:
    - system
    - views
  theme:
    - acm_demo_theme
id: views_block__products_products_block_2
theme: acm_demo_theme
region: content
weight: -1
provider: null
plugin: 'views_block:products-products_block'
settings:
  id: 'views_block:products-products_block'
  label: ''
  provider: views
  label_display: visible
  views_label: ''
  items_per_page: none
visibility:
  request_path:
    id: request_path
    pages: '<front>'
    negate: false
    context_mapping: {  }
