config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - views.view.frontpage
  module:
    - system
    - views
  theme:
    - acm_demo_theme
id: views_block__frontpage_block_1
theme: acm_demo_theme
region: content
weight: 0
provider: null
plugin: 'views_block:frontpage-block_1'
settings:
  id: 'views_block:frontpage-block_1'
  label: ''
  provider: views
  label_display: visible
  views_label: ''
  items_per_page: none
visibility:
  request_path:
    id: request_path
    pages: '<front>'
    negate: false
    context_mapping: {  }
