config_rewrite: replace
langcode: en
status: true
dependencies:
  module:
    - ctools
    - system
  theme:
    - acm_demo_theme
_core: {  }
id: acm_page_title
theme: acm_demo_theme
region: content
weight: -5
provider: null
plugin: page_title_block
settings:
  id: page_title_block
  label: 'Page title'
  provider: core
  label_display: '0'
visibility:
  'entity_bundle:node':
    id: 'entity_bundle:node'
    bundles:
      acm_product: acm_product
      article: article
    negate: true
    context_mapping:
      node: '@node.node_route_context:node'
  request_path:
    id: request_path
    pages: '<front>'
    negate: true
    context_mapping: {  }
